name: mobile_3_uas_kelompok_10
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  

  # Chart and visualization
  fl_chart: ^0.70.2

  # UI components
  curved_navigation_bar: ^1.0.6
  percent_indicator: ^4.2.4

  # Toast messages
  fluttertoast: ^8.2.10
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/bacground44.jpeg
    - assets/bacground44.jpeg
    - assets/bacground44.jpeg
    - assets/profile.jpeg
