// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8QLt22lRGtIBzB7m8avNprKP5sjy7vo',
    appId: '1:203264348210:web:9d03f25df7abb6e4e6ec2b',
    messagingSenderId: '203264348210',
    projectId: 'mobile3-uas-kelompok-10-38209',
    authDomain: 'mobile3-uas-kelompok-10-38209.firebaseapp.com',
    storageBucket: 'mobile3-uas-kelompok-10-38209.firebasestorage.app',
    measurementId: 'G-6FS0DT39JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzGxWTPZLW9yaVhE6rZodygEMnSjXwGpc',
    appId: '1:203264348210:android:07418a617340a11de6ec2b',
    messagingSenderId: '203264348210',
    projectId: 'mobile3-uas-kelompok-10-38209',
    storageBucket: 'mobile3-uas-kelompok-10-38209.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWC2kvJ-DaGKREQrburtEdcCjIquTDOfk',
    appId: '1:203264348210:ios:d76536fd61ef8e00e6ec2b',
    messagingSenderId: '203264348210',
    projectId: 'mobile3-uas-kelompok-10-38209',
    storageBucket: 'mobile3-uas-kelompok-10-38209.firebasestorage.app',
    iosBundleId: 'com.example.mobile3UasKelompok10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWC2kvJ-DaGKREQrburtEdcCjIquTDOfk',
    appId: '1:203264348210:ios:d76536fd61ef8e00e6ec2b',
    messagingSenderId: '203264348210',
    projectId: 'mobile3-uas-kelompok-10-38209',
    storageBucket: 'mobile3-uas-kelompok-10-38209.firebasestorage.app',
    iosBundleId: 'com.example.mobile3UasKelompok10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl8QLt22lRGtIBzB7m8avNprKP5sjy7vo',
    appId: '1:203264348210:web:817bb4aeea78b5c5e6ec2b',
    messagingSenderId: '203264348210',
    projectId: 'mobile3-uas-kelompok-10-38209',
    authDomain: 'mobile3-uas-kelompok-10-38209.firebaseapp.com',
    storageBucket: 'mobile3-uas-kelompok-10-38209.firebasestorage.app',
    measurementId: 'G-N7TF18NJF6',
  );
}
